### ISSUE TITLE
Package Not Working. Yielding No Result

### ISSUE THREAD

**Issue by una** [Stephn-R/sass-director-sublime#1]
Here's a visual: https://cloudup.com/cZUFK1C28kO

**Comment by Stephn-R** [comment]
Can you show me what is in the console?

**Comment by una** [comment]
Of course, sorry!

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 526, in run_
    return self.run()
  File "/Users/unakravets/Library/Application Support/Sublime Text 3/Packages/sass-director-sublime/sass-director.py", line 88, in run
    self.generateDirectories(dirs, view)
  File "/Users/unakravets/Library/Application Support/Sublime Text 3/Packages/sass-director-sublime/sass-director.py", line 58, in generateDirectories
    os.chdir(self.manifest_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/unakravets/Desktop/Dev/sassdirtest/main.scs'
```

it's cutting off the file name by 1 character (main.scs) but I'm not sure if that's the only error or not

**Comment by Stephn-R** [comment]
Looks like I just need to detect the OS and differentiate between forward-slash or back-slash. Not a problem! 

One bug fix coming up...

**Comment by Stephn-R** [comment]
@una Can you please try again?

**Comment by una** [comment]
Had some comments, but I'll open a new issue! This is working but I found some more bugs

**Comment by Stephn-R** [comment]
Not a problem! Bring in the bugs, lets try and get this to work well
